site_name: Начало работы
site_description: Начало работы с Docker
site_author: Docker
# site_url: https://squidfunk.github.io/mkdocs-material/

# Repository
repo_name: docker/getting-started
repo_url: https://github.com/docker/getting-started
edit_uri: ""

# Copyright
copyright: 'Авторские права &copy; 2020-2022 Docker'

# Configuration
theme:
  name: material
  language: ru
  palette:
    primary: blue
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.png
  logo: 'images/docker-labs-logo.svg'

extra_css:
  - css/styles.css
  - css/dark-mode.css

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Customization
extra:
  social:
    - type: github-alt
      link: https://github.com/docker/getting-started

# Extensions
markdown_extensions:
  - meta
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.footnotes
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: dockersamples
      repo: 101-tutorial
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list

# Page tree
nav:
  - Начало работы: tutorial/index.md
  - Наше приложение: tutorial/our-application/index.md
  - Обновление нашего приложения: tutorial/updating-our-app/index.md
  - Поделитесь нашим приложением: tutorial/sharing-our-app/index.md
  - Сохранение нашей БД: tutorial/persisting-our-data/index.md
  - Использование Bind Mounts: tutorial/using-bind-mounts/index.md
  - Мультиконтейнерные приложения: tutorial/multi-container-apps/index.md
  - Использование Docker Compose: tutorial/using-docker-compose/index.md
  - Лучшие практики создания образов: tutorial/image-building-best-practices/index.md
  - Что дальше??: tutorial/what-next/index.md
